name: ENC
version: ${project.version}
main: dev.anhcraft.enc.ENC
api-version: 1.13
depend: [SpaciousLib]
softdepend: [KeepMyLife,Essentials,WorldGuard,WorldEdit]
authors: [anhcraft]
description: Brings more enchantments to your servers
